FinalProject.UI.MVC/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalProject.DATA.EF;
using Microsoft.AspNet.Identity;

namespace FinalProject.UI.MVC.Controllers
{
    [Authorize]
    public class ReservationsController : Controller
    {
        private FinalProjectEntities db = new FinalProjectEntities();

        // GET: Reservations
        public ActionResult Index()
        {
            if (User.IsInRole("Pet Owner"))
            {
                var userId = User.Identity.GetUserId();

                var POReservations = db.Reservations.Where(x => x.Pet.OwnerId == userId).Include(r => r.Location).Include(r => r.Pet);
                return View(POReservations.ToList());
            }
            var reservations = db.Reservations.Include(r => r.Location).Include(r => r.Pet);
            return View(reservations.ToList());
        }

        // GET: Reservations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        //Custom DatePick View Here ++++
        [Authorize(Roles = "Admin, Pet Owner")]
        public ActionResult DatePick()
        {
            return View();
        }

        [Authorize(Roles = "Admin, Pet Owner")]
        [HttpPost]
        public ActionResult DatePick(DateTime resDate)
        {

            return RedirectToAction("Create", new { resDate = resDate });
        }

        
        // GET: Reservations/Create
        [Authorize(Roles ="Admin, Pet Owner")]
        public ActionResult Create(DateTime resDate)
        {
            ViewBag.ResDate = resDate; //This allows the date to be displayed in the view

            if (User.IsInRole("Pet Owner"))
            {
                //Used to filter the pets list in the case of user being a PO
                var userId = User.Identity.GetUserId();

                //This is the filtering for reservations to match the selected date and check that it's LESS than the res limit
                var locsList = db.Locations.Where(x => x.Reservations.Where(y => y.ReservationDate == resDate && y.LocationId == x.LocationId).Count() < x.ReservationLimit);
                
                ViewBag.LocationId = new SelectList(locsList, "LocationId", "LocationName");
                //This .Where ensures owners only see their own pets
                ViewBag.PetId = new SelectList(db.Pets.Where(x => x.OwnerId == userId), "PetId", "AssetName");
                return View();
            }

            //this will only run (and return the default list) if the user ISN'T a PO
            //These 2 lists aren't filtered because we don't want those restrictions to apply to admins
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "LocationName");
            ViewBag.PetId = new SelectList(db.Pets, "PetId", "AssetName");
            return View();
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReservationId,PetId,LocationId,ReservationDate,SpecialRequests")] Reservation reservation)
        {
            
            if (ModelState.IsValid)
            {
                db.Reservations.Add(reservation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "LocationName", reservation.LocationId);
            ViewBag.PetId = new SelectList(db.Pets, "PetId", "AssetName", reservation.PetId);
            return View(reservation);
        }

        // GET: Reservations/Edit/5
        [Authorize(Roles = "Admin, Employee")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "LocationName", reservation.LocationId);
            ViewBag.PetId = new SelectList(db.Pets, "PetId", "AssetName", reservation.PetId);
            return View(reservation);
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReservationId,PetId,LocationId,ReservationDate,SpecialRequests")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reservation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LocationId = new SelectList(db.Locations, "LocationId", "LocationName", reservation.LocationId);
            ViewBag.PetId = new SelectList(db.Pets, "PetId", "AssetName", reservation.PetId);
            return View(reservation);
        }

        // GET: Reservations/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reservation reservation = db.Reservations.Find(id);
            db.Reservations.Remove(reservation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinalProject.UI.MVC/Views/Reservations/Create.cshtml
@model FinalProject.DATA.EF.Reservation

@{
    ViewBag.Title = "Making a Reservation for: " + String.Format("{0: dddd MMMM d, yyyy}", ViewBag.ResDate);
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Reservation Details</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @*@Html.LabelFor(model => model.PetId, "PetId", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class = "control-label col-md-2">Pet Name</div>
            <div class="col-md-10">
                @Html.DropDownList("PetId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PetId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.LocationId, "LocationId", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="control-label col-md-2">Available Locations</div>
            <div class="col-md-10">
                @Html.DropDownList("LocationId", null, "*Locations with open reservation slots", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <input type="hidden" value="@ViewBag.ResDate" name="ReservationDate"/>
        
        @* Reservation Date is already determined so this isn't needed *@
        @*<div class="form-group">
            @Html.LabelFor(model => model.ReservationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReservationDate, new { htmlAttributes = new { @class = "form-control", id = "datepicker" } })
                @Html.ValidationMessageFor(model => model.ReservationDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.SpecialRequests, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SpecialRequests, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SpecialRequests, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Make Reservation" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="text-right">
    @Html.ActionLink("Cancel Reservation", "Index", null, new { @class = "btn btn-danger btn-outline" })
</div>

FinalProject.UI.MVC/Views/Reservations/DatePick.cshtml
@{
    ViewBag.Title = "Choose a Reservation Date";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <input id="datepicker" name="resDate" class="col-md-4 col-md-offset-4 col-sm-12" />
    </div>

    <br />
    <div class="form-group">
        <div class="text-center">
            <input type="submit" value="Select Date" class="btn btn-default" />
        </div>
    </div>
}

<div id="reservationBackButton">
    @Html.ActionLink("Back to All Reservations", "Index", "Reservations", null, new { @class = "btn btn-danger btn-outline" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <!--jQuery UI-->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!--jQuery DatePicker Script-->
    <script>
        $(function () {
            $("#datepicker").datepicker();
            $("#anim").on("change", function () {
                $("#datepicker").datepicker("option", "drop", $(this).val());
            });
        });
    </script>
}

FinalProject.UI.MVC/Views/Reservations/Delete.cshtml
@model FinalProject.DATA.EF.Reservation

@{
    ViewBag.Title = "Delete Reservation For " + Model.Pet.AssetName;
}

<h2>@ViewBag.Title</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.ReservationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReservationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SpecialRequests)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecialRequests)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location.LocationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.LocationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pet.AssetName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pet.AssetName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to Reservations", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

FinalProject.UI.MVC/Views/Reservations/Details.cshtml
@model FinalProject.DATA.EF.Reservation

@{
    ViewBag.Title = Html.DisplayFor(model => model.ReservationDate)+" Reservation Details";
}

<h2 class="text-center">@ViewBag.Title</h2>

<div>
    <dl >
        <dt>
            @Html.DisplayNameFor(model => model.ReservationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReservationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SpecialRequests)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecialRequests)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location.LocationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.LocationName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pet.AssetName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pet.AssetName)
        </dd>

    </dl>
</div>
<p>
    @if (User.IsInRole("Admin") || User.IsInRole("Employee"))
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.ReservationId }, new { @class = "btn btn-white" })
    }
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-white" })
</p>

FinalProject.UI.MVC/Views/Reservations/Edit.cshtml
@model FinalProject.DATA.EF.Reservation

@{
    ViewBag.Title = "Edit Reservation";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Editing @Model.Pet.AssetName's Reservation (By @Model.Pet.UserDetail.FullName)</h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ReservationId)

        @if (User.IsInRole("Admin") || User.IsInRole("Pet Owner"))
        {
            <div class="form-group">
                @*@Html.LabelFor(model => model.PetId, "PetId", htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class = "control-label col-md-2">Pet Name</div>
                <div class="col-md-10">
                    @Html.DropDownList("PetId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PetId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @*@Html.LabelFor(model => model.LocationId, "LocationId", htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="control-label col-md-2">Daycare Location</div>
                <div class="col-md-10">
                    @Html.DropDownList("LocationId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LocationId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ReservationDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ReservationDate, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ReservationDate, "", new { @class = "text-danger" })
                </div>
            </div>
        }
        <div class="form-group">
            @Html.LabelFor(model => model.SpecialRequests, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SpecialRequests, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SpecialRequests, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save Changes" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="text-right">
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-danger btn-outline" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FinalProject.UI.MVC/Views/Reservations/Index.cshtml
@model IEnumerable<FinalProject.DATA.EF.Reservation>

@{
    ViewBag.Title = User.IsInRole("Pet Owner") ? "Your Reservations" : "All Reservations";
}

<h2 class="text-center">@ViewBag.Title</h2>
@if (User.IsInRole("Admin") || User.IsInRole("Pet Owner"))
{
    <div>
        @Html.ActionLink("Make a Reservation", "DatePick", null, new { @class="btn btn-special"})
    </div>
    <br />
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ReservationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SpecialRequests)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Location.LocationName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pet.AssetName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ReservationDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SpecialRequests)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location.LocationName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pet.AssetName)
            </td>
            <td>

                @Html.ActionLink("Info", "Details", new { id = item.ReservationId })
                @if (User.IsInRole("Admin") || User.IsInRole("Employee"))
                {
                    @:|
                    @Html.ActionLink("Edit", "Edit", new { id = item.ReservationId })

                    if (User.IsInRole("Admin"))
                    {
                        @:|
                        @Html.ActionLink("Delete", "Delete", new { id = item.ReservationId })
                    }

                }

            </td>
        </tr>
    }

</table>