FinalProject.UI.MVC/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalProject.DATA.EF;

namespace FinalProject.UI.MVC.Controllers
{
    public class LocationsController : Controller
    {
        private FinalProjectEntities db = new FinalProjectEntities();

        // GET: Locations
        public ActionResult Index()
        {
            return View(db.Locations.ToList());
        }

        // GET: Locations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // GET: Locations/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Locations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "LocationId,LocationName,Address,City,State,ZipCode,ReservationLimit")] Location location)
        {
            if (ModelState.IsValid)
            {
                db.Locations.Add(location);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(location);
        }

        // GET: Locations/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "LocationId,LocationName,Address,City,State,ZipCode,ReservationLimit")] Location location)
        {
            if (ModelState.IsValid)
            {
                db.Entry(location).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(location);
        }

        // GET: Locations/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Location location = db.Locations.Find(id);
            if (location == null)
            {
                return HttpNotFound();
            }
            return View(location);
        }

        // POST: Locations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Location location = db.Locations.Find(id);
            db.Locations.Remove(location);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinalProject.UI.MVC/Controllers/PetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinalProject.DATA.EF;
using FinalProject.UI.MVC.Utilities;
using Microsoft.AspNet.Identity;

namespace FinalProject.UI.MVC.Controllers
{
    [Authorize]
    public class PetsController : Controller
    {
        private FinalProjectEntities db = new FinalProjectEntities();

        // GET: Pets
        public ActionResult Index()
        {
            if (User.IsInRole("Pet Owner"))
            {
                var userId = User.Identity.GetUserId();

                var POPets = db.Pets.Where(x => x.OwnerId == userId).Include(p => p.UserDetail);
                return View(POPets.ToList());
            }
            var pets = db.Pets.Include(p => p.UserDetail);
            return View(pets.ToList());
        }

        // GET: Pets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pet pet = db.Pets.Find(id);
            if (pet == null)
            {
                return HttpNotFound();
            }
            return View(pet);
        }

        // GET: Pets/Create
        [Authorize(Roles = "Admin, Pet Owner")]
        public ActionResult Create()
        {
            if (User.IsInRole("Pet Owner"))
            {
                var userId = User.Identity.GetUserId();
                ViewBag.OwnerId = new SelectList(db.UserDetails.Where(x => x.UserId == userId), "UserId", "FullName");
                return View();

            }

            ViewBag.OwnerId = new SelectList(db.UserDetails, "UserId", "FullName");
            return View();
        }

        // POST: Pets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Pet Owner")]
        public ActionResult Create([Bind(Include = "PetId,AssetName,OwnerId,AssetPhoto,SpecialNotes,IsActive,DateAdded")] Pet pet, HttpPostedFileBase petImg)
        {
            pet.DateAdded = DateTime.Now;
            pet.IsActive = true;

            if (ModelState.IsValid)
            {
                #region File Upload
                string file = "NoImage.png";

                if (petImg != null)
                {
                    file = petImg.FileName;
                    string ext = file.Substring(file.LastIndexOf('.'));
                    string[] goodExts = { ".jpeg", ".jpg", ".png", ".gif" };
                    //check that the uploaded file is in our approved list of extensions
                    if (goodExts.Contains(ext.ToLower()) && petImg.ContentLength <= 4194304)//check thet the file is less than 4mb, is the default allowed file size by .NET
                    {
                        //greate a new file name using a GUID
                        file = Guid.NewGuid() + ext;
                        #region Rezise Image
                        string savePath = Server.MapPath("~/Content/images/pets/");

                        Image convertedImage = Image.FromStream(petImg.InputStream);
                        int maxImageSize = 500; //the full size image width
                        int maxThumbSize = 100; //thumbnail size width

                        ImageService.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);
                        #endregion
                    }

                }
                //no matter what update the photo url with the value of the file variable
                pet.AssetPhoto = file;
                #endregion


                db.Pets.Add(pet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //This sends back the filtered ownerid (for POs) if the object doesn't pass validation
            if (User.IsInRole("Pet Owner"))
            {
                var userId = User.Identity.GetUserId();
                ViewBag.OwnerId = new SelectList(db.UserDetails.Where(x => x.UserId == userId), "UserId", "FullName");
                return View();

            }

            ViewBag.OwnerId = new SelectList(db.UserDetails, "UserId", "FullName", pet.OwnerId);
            return View(pet);
        }

        // GET: Pets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pet pet = db.Pets.Find(id);
            if (pet == null)
            {
                return HttpNotFound();
            }

            if (User.IsInRole("Pet Owner"))
            {
                var userId = User.Identity.GetUserId();
                ViewBag.OwnerId = new SelectList(db.UserDetails.Where(x => x.UserId == userId), "UserId", "FullName", pet.OwnerId);
                return View(pet);
            }

            ViewBag.OwnerId = new SelectList(db.UserDetails, "UserId", "FullName", pet.OwnerId);
            return View(pet);
        }

        // POST: Pets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PetId,AssetName,OwnerId,AssetPhoto,SpecialNotes,IsActive,DateAdded")] Pet pet, HttpPostedFileBase petImg)
        {
            if (ModelState.IsValid)
            {
                #region File Upload
                string file = "NoImage.png";

                if (petImg != null)
                {
                    file = petImg.FileName;
                    string ext = file.Substring(file.LastIndexOf('.'));
                    string[] goodExts = { ".jpeg", ".jpg", ".png", ".gif" };
                    //check that the uploaded file is in our approved list of extensions
                    if (goodExts.Contains(ext.ToLower()) && petImg.ContentLength <= 4194304)//check thet the file is less than 4mb, is the default allowed file size by .NET
                    {
                        //greate a new file name using a GUID
                        file = Guid.NewGuid() + ext;
                        #region Rezise Image
                        string savePath = Server.MapPath("~/Content/images/pets/");

                        Image convertedImage = Image.FromStream(petImg.InputStream);
                        int maxImageSize = 500; //the full size image width
                        int maxThumbSize = 100; //thumbnail size width

                        ImageService.ResizeImage(savePath, file, convertedImage, maxImageSize, maxThumbSize);
                        #endregion
                        if (pet.AssetPhoto != null && pet.AssetPhoto != "NoImage.png")
                        {
                            //string path = Server.MapPath("~/Content/imgstore/books/");
                            ImageService.Delete(savePath, pet.AssetPhoto);

                        }
                        pet.AssetPhoto = file;
                    }

                }
                //no matter what update the photo url with the value of the file variable

                #endregion

                db.Entry(pet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            if (User.IsInRole("Pet Owner"))
            {
                var userId = User.Identity.GetUserId();
                ViewBag.OwnerId = new SelectList(db.UserDetails.Where(x => x.UserId == userId), "UserId", "FirstName", pet.OwnerId);
                return View(pet);
            }

            ViewBag.OwnerId = new SelectList(db.UserDetails, "UserId", "FirstName", pet.OwnerId);
            return View(pet);
        }

        // GET: Pets/Delete/5
        [Authorize(Roles = "Admin, Pet Owner")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pet pet = db.Pets.Find(id);
            if (pet == null)
            {
                return HttpNotFound();
            }
            return View(pet);
        }

        // POST: Pets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pet pet = db.Pets.Find(id);
            pet.IsActive = false;
            db.Entry(pet).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Uncomment this when hard deleting
        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

FinalProject.UI.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title | Paws N Claws</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="A mock website for managing reservations at pet hotels" />
    <meta name="keywords" content="dogs, cats, boarding, overnight, pets, kansas city, customer service" />
    <meta name="author" content="Sawyer Gobin" />

    <link href="https://fonts.googleapis.com/css?family=Raleway:100,300,400,700" rel="stylesheet">

    @* All these are included in the bundle.config *@
    @*<!-- Animate.css -->
    <link rel="stylesheet" href="~/Content/css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="~/Content/css/icomoon.css">
    <!-- Themify Icons-->
    <link rel="stylesheet" href="~/Content/css/themify-icons.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="~/Content/css/bootstrap.css">
    <!-- Magnific Popup -->
    <link rel="stylesheet" href="~/Content/css/magnific-popup.css">
    <!-- Owl Carousel  -->
    <link rel="stylesheet" href="~/Content/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Content/css/owl.theme.default.min.css">
    <!-- Theme style  -->
    <link rel="stylesheet" href="~/Content/css/style.css">*@
    @Styles.Render("~/Content/styles")

    <!--jQuery UI Style-->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/cupertino/jquery-ui.css">

    <!--Custom StyleSheet-->
    <link rel="stylesheet" href="~/Content/css/custom.css">
    <!-- Modernizr JS -->
    @Scripts.Render("~/bundles/modernizr")
    @*<script src="~/Content/js/modernizr-2.6.2.min.js"></script>*@

    <!-- FOR IE9 below -->
    <!--[if lt IE 9]>
    <script src="js/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    @* PreLoader *@
    <div class="gtco-loader"></div>

    <div id="page">
        <nav class="gtco-nav" role="navigation">
            <div class="gtco-container">

                <div class="row">
                    <div class="col-sm-4 col-xs-12">
                        <div id="gtco-logo"><a href="@Url.Action("Index", "Home")"><img src="~/Content/images/PNCLogoTiny40x40.png" alt="Paws N Claws Logo"></a></div>
                        @Html.Partial("_LoginPartial")
                    </div>
                    <div class="col-xs-8 text-right menu-1">
                        <ul>
                            <li class="active"><a href="@Url.Action("Index", "Home")">Home</a></li>

                            @* Admin Only Dropdown *@
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="has-dropdown">
                                    <a href="javascript:void(0)">ADMIN</a>
                                    <ul class="dropdown">
                                        <li><a href="@Url.Action("Index", "UsersAdmin")">Users Admin</a></li>
                                        <li><a href="@Url.Action("Index", "RolesAdmin")">Roles Admin</a></li>
                                        <li><a href="@Url.Action("Create", "Locations")">Add New Daycare</a></li>
                                    </ul>
                                </li>
                            }
                            @* Different Dropdowns here depending on role *@
                            @if (User.IsInRole("Pet Owner"))
                            {
                                <li class="has-dropdown">
                                    <a href="javascript:void(0)">My Pets</a>
                                    <ul class="dropdown">
                                        <li><a href="@Url.Action("Index", "Pets")">All My Pets</a></li>
                                        <li><a href="@Url.Action("Create", "Pets")">Add New Pet</a></li>
                                    </ul>
                                </li>
                            }
                            else if (User.IsInRole("Admin") || User.IsInRole("Employee"))
                            {
                                <li class="has-dropdown">
                                    <a href="javascript:void(0)">Pets</a>
                                    <ul class="dropdown">
                                        <li><a href="@Url.Action("Index", "Pets")">All Pets</a></li>
                                        @if (User.IsInRole("Admin"))
                                        {
                                            <li><a href="@Url.Action("Create", "Pets")">Add New Pet</a></li>
                                        }
                                    </ul>
                                </li>
                            }

                            @if (Request.IsAuthenticated)
                            {
                                <li><a href="@Url.Action("Index","Reservations")">Reservations</a></li>
                            }
                            <li><a href="@Url.Action("Index", "Locations")">Our Locations</a></li>
                            @if (Request.IsAuthenticated)
                            {
                                <li><a href="@Url.Action("Contact", "Home")">Contact</a></li>
                            }


                        </ul>
                    </div>
                </div>

            </div>
        </nav>

        <div id="mainContent">
            @RenderBody()
        </div>

        <footer id="gtco-footer" class="gtco-section" role="contentinfo">
            <div class="gtco-container">
                @if (Request.IsAuthenticated)
                {
                    <div class="row row-pb-sm">
                        <div class="col-md-8 col-md-offset-2 gtco-cta text-center">
                            <h3>Questions? Ask us!</h3>
                            <p><a href="@Url.Action("Contact", "Home")" class="btn btn-white btn-outline">Contact Us</a></p>
                        </div>
                    </div>
                }
                <div class="row row-pb-md">
                    <div class="col-md-6 gtco-widget gtco-footer-paragraph text-center">
                        <h3>Paws N Claws Daycare Group</h3>
                        <p>Where your fur family is our family</p>
                        <p>Site Documentation <a href="~/Content/SawyerGobinDocumentation.pdf" target="_blank">HERE</a></p>
                    </div>
                    <div class="col-md-6 gtco-footer-link">
                        <div class="row">
                            <div class="col-md-6">
                                <ul class="gtco-list-link">
                                    <li>Paws N Claws Home Page: <a href="@Url.Action("Index", "Home")" class="ti-home"></a></li>
                                    <li>My Portfolio Site: <a href="http://www.sawyergobin.com" target="_blank" class="ti-desktop"></a></li>
                                    <li>My Public Repositories: <a href="https://github.com/sawyergobin?tab=repositories" target="_blank" class="ti-ink-pen"></a></li>
                                    <li>My LinkedIn Profile: <a href="https://www.linkedin.com/in/sawyer-gobin/" target="_blank" class="ti-linkedin"></a></li>
                                </ul>
                            </div>
                            <div class="col-md-6">
                                <p>
                                    <a>(234)-456-2342</a>
                                    <br>
                                    <a>ask4info@pnc.com</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="gtco-copyright">
                <div class="gtco-container">
                    <div class="row">
                        <div class="col-md-6 text-left">
                            <p><small>&copy; @DateTime.Now.Year By Sawyer Gobin. All Rights Reserved. </small></p>
                        </div>
                        <div class="col-md-6 text-right">
                            <p><small>Designed by <a href="http://freehtml5.co/" target="_blank">FreeHTML5.co</a> Converted and styled by <a href="http://www.sawyergobin.com">Sawyer Gobin</a></small> </p>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <div class="gototop js-top">
        <a href="#" class="js-gotop"><i class="icon-arrow-up"></i></a>
    </div>

    @* These are included in the bundle.config *@
    @*<!-- jQuery -->
    <script src="~/Content/js/jquery.min.js"></script>
    <!-- jQuery Easing -->
    <script src="~/Content/js/jquery.easing.1.3.js"></script>
    <!-- Bootstrap -->
    <script src="~/Content/js/bootstrap.min.js"></script>
    <!-- Waypoints -->
    <script src="~/Content/js/jquery.waypoints.min.js"></script>
    <!-- Carousel -->
    <script src="~/Content/js/owl.carousel.min.js"></script>
    <!-- Magnific Popup -->
    <script src="~/Content/js/jquery.magnific-popup.min.js"></script>
    <script src="~/Content/js/magnific-popup-options.js"></script>
    <!-- Main -->
    <script src="~/Content/js/main.js"></script>*@
    @Scripts.Render("~/Content/scripts")


    @RenderSection("scripts", required: false)
</body>

<!--
    Cube Template by FreeHTML5.co
    Twitter: http://twitter.com/gettemplateco
    URL: http://freehtml5.co
-->
</html>

FinalProject.UI.MVC/Views/Shared/_OriginalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>